name: Arduino Library Deploy
description: A Docker-based GitHub Action to validate, merge PRs, and create releases.
branding:
  icon: "archive"
  color: "green"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for API requests."
    required: true
  lint-mode:
    description: "The library manager mode for arduino-lint. Can be {submit|update|false}."
    required: false
    default: "update"
  source-branch:
    description: "The source branch for auto-creating PRs on tag push."
    required: false
    default: "develop"
  target-branch:
    description: "The target branch for auto-creating PRs on tag push."
    required: false
    default: "main"

runs:
  using: "docker"
  image: "Dockerfile"
